const CONFIG={contactEmail:"YOUR_EMAIL@example.com"};

async function fetchPigs(dataUrl){const r=await fetch(dataUrl,{cache:"no-store"});if(!r.ok)throw new Error(`Unable to load inventory (${r.status})`);const pigs=await r.json();return [...pigs].sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999))}
function statusClass(status=""){const s=status.toLowerCase();if(s.includes("pending")||s.includes("reserved"))return"pending";if(s.includes("sold"))return"sold";return"available"}
function hasVideo(p){if(typeof p.videoAvailable==="boolean")return p.videoAvailable&&Boolean((p.youtube||"").trim());return Boolean((p.youtube||"").trim())}
function pedigree(p){return p.pedigree||[p.sire,p.dam].filter(Boolean).join(" × ")}
function shortCopy(p){return p.title||p.description||"View the full lot for breeder notes and additional information."}
function youtubeEmbedUrl(url){if(!url)return"";try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return`https://www.youtube.com/embed/${u.pathname.slice(1)}`;if(u.searchParams.get("v"))return`https://www.youtube.com/embed/${u.searchParams.get("v")}`;if(u.pathname.includes("/embed/"))return url;if(u.pathname.includes("/shorts/"))return`https://www.youtube.com/embed/${u.pathname.split("/shorts/")[1]}`}catch(e){}return""}
function displayPrice(p){return p.price||"Contact for Price"}

async function buildCatalog(){const grid=document.getElementById("pig-grid");if(!grid)return;const pigs=await fetchPigs(document.body.dataset.dataUrl||"../data/pigs.json");grid.innerHTML="";pigs.forEach(p=>{const state=statusClass(p.status);const card=document.createElement("article");card.className=`pig-card ${state==="pending"?"pending-card":""} ${state==="sold"?"sold-card":""}`;const overlay=state==="pending"?'<div class="status-overlay"><span>SALE PENDING</span></div>':state==="sold"?'<div class="status-overlay"><span>SOLD</span></div>':"";card.innerHTML=`<div class="pig-card-media"><img src="../${p.photo}" alt="Lot ${p.lot}">${overlay}${hasVideo(p)?'<span class="video-pill">▶ Video</span>':""}</div><div class="pig-card-content"><span class="badge ${state}">${p.status}</span><h2>Lot ${p.lot}</h2><p class="pig-card-meta">${[p.sex,p.breed].filter(Boolean).join(" • ")||"Show Pig"}</p><p class="pig-card-price">${displayPrice(p)}</p>${pedigree(p)?`<p class="pig-card-meta"><strong>Pedigree:</strong> ${pedigree(p)}</p>`:""}<p class="pig-card-copy">${shortCopy(p)}</p><a class="button full" href="tag.html?lot=${encodeURIComponent(p.lot)}">View Lot</a></div>`;grid.appendChild(card)})}

async function buildDetail(){const root=document.getElementById("lot-detail");if(!root)return;const lot=new URLSearchParams(location.search).get("lot");const pigs=await fetchPigs(document.body.dataset.dataUrl||"../data/pigs.json");const p=pigs.find(x=>String(x.lot)===String(lot));if(!p){root.innerHTML=`<div class="empty-state">Lot ${lot} could not be found.</div>`;return}const state=statusClass(p.status),embed=youtubeEmbedUrl(p.youtube),interest=`../contact.html?lot=${encodeURIComponent(p.lot)}&price=${encodeURIComponent(p.price||"")}`;const explainer=state==="pending"?'<div class="status-explainer pending">A buyer is currently working to purchase this pig. Contact us about similar pigs or to be notified if availability changes.</div>':state==="sold"?'<div class="status-explainer sold">This pig has sold. Contact us and we can help you find a similar prospect.</div>':"";root.innerHTML=`<div class="detail-grid"><div class="detail-media"><img src="../${p.photo}" alt="Lot ${p.lot}"><div class="video-wrap">${embed?`<iframe class="video-frame" src="${embed}" title="Lot ${p.lot} video" allowfullscreen></iframe>`:'<div class="no-video">Video coming soon.</div>'}</div></div><aside class="detail-panel"><span class="badge ${state}">${p.status}</span><h1>Lot ${p.lot}</h1><p class="detail-subtitle">${[p.sex,p.breed].filter(Boolean).join(" • ")}</p>${explainer}<div class="quick-facts"><div class="fact fact-wide"><span>Pedigree</span><strong>${pedigree(p)||"—"}</strong></div><div class="fact"><span>DOB</span><strong>${p.dob||"—"}</strong></div><div class="fact"><span>Video</span><strong>${hasVideo(p)?"Available":"Coming soon"}</strong></div></div><div class="price">${displayPrice(p)}</div><div class="notes"><h2>Breeder's Notes</h2><p>${p.description||"Contact Impact Livestock for more information about this lot."}</p></div>${state==="available"?`<a class="button full" href="${interest}">RESERVE THIS PIG</a>`:`<a class="button secondary full" href="../contact.html?similar=${encodeURIComponent(p.lot)}">ASK ABOUT SIMILAR PIGS</a>`}</aside></div>`;if(state==="available"){document.body.classList.add("has-sticky-cta");const sticky=document.getElementById("sticky-cta");if(sticky)sticky.innerHTML=`<a class="button full" href="${interest}">RESERVE LOT ${p.lot}</a>`}}

function setupContactPage(){const form=document.getElementById("interest-form");if(!form)return;const params=new URLSearchParams(location.search),lot=params.get("lot")||"",price=params.get("price")||"",similar=params.get("similar")||"";document.getElementById("lot").value=lot||similar;document.getElementById("price").value=lot?price:"";if(lot){document.getElementById("contact-intro").textContent=`Submit your reservation request for Lot ${lot}.`;document.getElementById("submit-label").textContent="SUBMIT RESERVATION REQUEST"}else if(similar){document.getElementById("contact-intro").textContent=`Tell us what you liked about Lot ${similar} and we'll help you find a similar pig.`;document.getElementById("submit-label").textContent="ASK ABOUT SIMILAR PIGS"}form.addEventListener("submit",e=>{e.preventDefault();alert("Visual beta only. Next we will connect this form to your Google Sheet and SMS notification.")})}
document.addEventListener("DOMContentLoaded",()=>{buildCatalog();buildDetail();setupContactPage()});
